# llamafactory-cli train examples/train_full/llama3_full_sft.yaml

### model
model_name_or_path: [your checkpoint directory, example: meta-llama/Llama-3.1-8B-Instruct]
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: [your dataset name, please define it in dataset_info.json]
template: llama3
cutoff_len: 2304
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: [your output directory for model ckpt. Example: saves/llama3-8b/full/dpo]
logging_steps: 5
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 1.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

## eval
val_size: 0.04
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 200
