# llamafactory-cli train examples/train_full/qwen2.5_3b_full_sft.yaml

### model
model_name_or_path: [your checkpoint directory, example: Qwen/Qwen2.5-3B-Instruct]
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: [your dataset name, please define it in dataset_info.json]
template: qwen
cutoff_len: 2048
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir:  [your output directory for model ckpt. Example: saves/qwen2.5-3b/full/sft]
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 2.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

## eval
val_size: 0.03
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 50
